### ISSUE TITLE
Any way to include menu bar apps in RunningApplications?

### ISSUE THREAD

**Issue by rben01** [laconalabs/lacona-phrases#1]
Not sure if this is the right place for this... but it would be great if RunningApplications also included menu bar apps so that they could be quit from Lacona. As it is, I believe RunningApplications only includes apps visible in the Dock and available from Cmd-Tab.

**Comment by brandonhorst** [comment]
It's harder but it's likely possible. This has been requested quite a bit so I'm going to dive into it.

https://developer.apple.com/library/mac/documentation/AppKit/Reference/NSRunningApplication_Class/

**Comment by rben01** [comment]
I think this Terminal command may do the trick. I haven't really tested it much, but at first glance it looks like it works.

`ps -Aro comm | grep -E "^~?/Applications" | sed -r "s:^/([^/]+/)*([^/]+\.app)/?.*$:\2:" | sort | uniq`

**Comment by brandonhorst** [comment]
Wow - quite a command.

I have an implementation working (using `NSRunningApplication` instead), but thank you for the suggestion! It should be available in the next version.
